### ISSUE TITLE
Compilation Error: Cannot find module

### ISSUE THREAD

**Issue by Frikki** [TylorS167/typed-test#3]
Running tests throws compilation errors when using aliases.

**Code to reproduce the issue:**

Add an alias to _tsconfig.json_:

```json
{
  ...
  "compilerOptions": {
    ...
    "paths": {
      "tmp/*": [ "./tmp/*" ]
    }
    ...
  }
  ...
}
```

Create a test file and an implementation file in a folder _tmp_.

_File: ./tmp/a.ts_

```ts
export function a(): boolean {
  return true
}

```

_File: ./tmp/a.test.ts_

```ts
import { a } from 'tmp/a'

export test: Test = describe(`a`, [
  it(`returns true`, ({ ok }) => {
    ok(a())
  })
])
```

Execute `./node_modules/.bin/typed-test 'tmp/a.test.ts'`

**Expected behavior:**

Tests run without compilation errors.

**Actual behavior:**

```
Error: Cannot find module 'tmp/a'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/temporary/tests/tmp/a.test.js:1:11)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Versions of packages used:**

`typescript@2.5.3`
`@typed/test@2.5.0`

**Comment by TylorS** [comment]
The latest version of the library, which has finally become stable, has alias mapping built-in and should work automatically for both node or browsers!
